const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const {chromium}=require(require('os').homedir()+'/AppData/Roaming/npm/node_modules/playwright');
const root=path.resolve(__dirname,'..'), url='https://jimeng.jianying.com/ai-tool/work-detail/7677836118599027978?type=video&workDetailType=Image&itemType=9';
(async()=>{const context=await chromium.launchPersistentContext(fs.mkdtempSync(path.join(os.tmpdir(),'clip140-')),{executablePath:require('os').homedir()+'/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe',headless:true,args:[`--disable-extensions-except=${root}`,`--load-extension=${root}`]});
try {const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');const page=await context.newPage();
try {await page.goto(url,{timeout:25000,waitUntil:'domcontentloaded'});await page.waitForTimeout(3000);console.log('LIVE',page.url(),(await page.locator('body').innerText()).slice(0,500));await page.screenshot({path:path.join(root,'output/playwright/jimeng-live-140.png')});console.log('LIVE DOM',await page.locator('div,span,p').evaluateAll(es=>es.filter(e=>e.textContent.trim()==='图片提示词').map(e=>({html:e.outerHTML,parent:e.parentElement.outerHTML.slice(0,7000)}))));await worker.evaluate(async u=>{const [t]=await chrome.tabs.query({url:u});await chrome.scripting.executeScript({target:{tabId:t.id},files:['lib/Readability.js','lib/turndown.js','content/extractor.js']});console.log('live injected');},url);const liveResult = await worker.evaluate(async u=>{const [t]=await chrome.tabs.query({url:u});return chrome.tabs.sendMessage(t.id,{type:'CLIP Extract Content'});},url);assert(liveResult.text.startsWith('暗黑细腻厚涂风格'));assert(!/做同款|请先登录|图片 5.0 Pro/.test(liveResult.markdown));console.log('PASS live reported work prompt only');}catch(e){console.log('LIVE unavailable',e.message);}
let html='';await page.route('https://jimeng.jianying.com/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:html}));
async function load(value){html=value;await page.goto(url);await worker.evaluate(async u=>{const [t]=await chrome.tabs.query({url:u});await chrome.scripting.executeScript({target:{tabId:t.id},files:['lib/Readability.js','lib/turndown.js','content/extractor.js']});},url);}
async function extract(){return worker.evaluate(async u=>{const [t]=await chrome.tabs.query({url:'https://jimeng.jianying.com/*'});return chrome.tabs.sendMessage(t.id,{type:'CLIP Extract Content',pageUrl:u});},url);}
const block=v=>`<div class="detail-info"><div class="prompt-tip">图片提示词</div><div class="prompt-value">${v}</div></div>`;
await load('<nav>导航正文</nav><article>'+('推荐污染'.repeat(500))+'</article>'+block('猫'));assert.equal((await extract()).markdown,'图片提示词：\n猫');
await load(block('原提示词')+'<aside class="recommend">'+block('推荐')+'</aside>');assert.equal((await extract()).text,'原提示词');
await load(block('甲')+block('乙'));assert.equal((await extract()).markdown,'');
await load(block(''));assert.equal((await extract()).markdown,'');
await load('<nav>只有导航</nav>');assert.equal((await extract()).markdown,'');
await load(block('旧内容'.repeat(100)));await page.evaluate(h=>setTimeout(()=>document.body.innerHTML=h,400),block('新'));assert.equal((await extract()).text,'新');
await load(block('旧'));const pending=extract();await page.waitForTimeout(300);await page.evaluate(()=>history.pushState({},'', '/ai-tool/work-detail/999'));assert.match((await pending).error,/切换/);
await load('<article>'+'推荐污染'.repeat(500)+'</article>'+block('首页弹层原提示词'));
await page.evaluate(()=>history.replaceState({},'', '/ai-tool/home'));
assert.equal((await extract()).text,'首页弹层原提示词');
await page.evaluate(()=>document.querySelector('.detail-info').remove());
assert.equal((await extract()).text,'');
console.log('PASS homepage overlay and missing prompt never fall back to article');
console.log('PASS real extension extraction: short, recommendations, multi-instance, empty, navigation, SPA latest and URL change');
await worker.evaluate(()=>{globalThis.__writes=[];globalThis.__reads=[];const native=fetch;globalThis.fetch=async(u,o={})=>{if(!String(u).startsWith('https://open.feishu.cn/'))return native(u,o);__reads.push(String(u));let data;if(String(u).includes('tenant_access_token'))return new Response(JSON.stringify({code:0,tenant_access_token:'mock',expire:3600}));if(String(u).includes('/fields')){const fields=[{field_name:'分类',type:4,property:{options:[{name:'视频提示词'}]}},{field_name:'主分类',type:3,property:{options:[{name:'视频-成品提示词'}]}},{field_name:'子分类',type:globalThis.__badType?4:3,property:{options:[{name:'女频网红'}]}},{field_name:'使用模型',type:3,property:{options:[{name:'seedance2.5'}]}}];data=String(u).includes('page_token')?{items:fields.slice(2)}:{items:fields.slice(0,2),has_more:true,page_token:'nextFields'};}else if(String(u).includes('/records')){const fields=JSON.parse(o.body).fields;for(const k of ['主分类','子分类','使用模型'])if(typeof fields[k]!=='string')throw Error('SingleSelect requires string');if(!Array.isArray(fields['分类']))throw Error('MultiSelect requires array');__writes.push(fields);data={record:{record_id:'fixture'}};}else data=String(u).includes('page_token')?{items:[{table_id:'tblFinal',name:'视频提示词-成品提示词'}]}:{items:[],has_more:true,page_token:'nextTables'};return new Response(JSON.stringify({code:0,data}));};return chrome.storage.local.set({feishu_clip_config:{appId:'fixture',appSecret:'fixture',appToken:'copy'},clip_taxonomy:{'视频提示词':{prefix:'视频',children:{'成品提示词':{table:'视频提示词-成品提示词',styles:['女频网红'],models:['seedance2.5']}}}}});});
const options=await context.newPage();await options.goto(`chrome-extension://${new URL(worker.url()).host}/options/options.html`);await options.locator('.taxonomy-card').waitFor();await options.locator('#sync-schema').click();await options.waitForFunction(()=>document.querySelector('#msg').textContent.includes('已读取'));assert.equal(await options.locator('.option-tag').count(),2);await options.locator('#save').click();
const payload={title:'fixture',url:'https://example.com',group:'视频提示词',subcategory:'成品提示词',style:'女频网红',model:'seedance2.5'};
const save=p=>options.evaluate(payload=>chrome.runtime.sendMessage({type:'CLIP Save To Feishu',payload}),p);
assert.equal((await save(payload)).ok,true);assert.equal((await save({...payload,model:'不存在'})).ok,false);await worker.evaluate(()=>globalThis.__badType=true);assert.equal((await save(payload)).ok,false);assert.equal(await worker.evaluate(()=>__writes.length),1);assert(await worker.evaluate(()=>__reads.some(u=>u.includes('nextTables'))&&__reads.some(u=>u.includes('nextFields'))));
await options.screenshot({path:path.join(root,'output/playwright/options-141.png'),fullPage:true});await options.setViewportSize({width:390,height:844});assert(await options.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));console.log('PASS schema pagination, selected table options, options UI, single-select protocol, invalid model and numeric schema rejection; no remote writes');
}finally{await context.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
